### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: simple_reminder.test

### ISSUE THREAD

**Issue by agateblue** [hitchtest/django-remindme-tests#1]
Hi !

Following the steps described in README,  I've cloned the two repositories and I'm stucked at:

```
cd /tmp/django-remindme/django-remindme-tests
hitch test simple_reminder.test
```

The full stack trace is:

```
user@computer:/tmp/django-remindme/django-remindme-tests$ hitch test simple_reminder.test 
Traceback (most recent call last):
  File "/tmp/django-remindme/.hitch/virtualenv/bin/hitchtest", line 9, in <module>
    load_entry_point('hitchtest==0.6.5', 'console_scripts', 'hitchtest')()
  File "/tmp/django-remindme/.hitch/virtualenv/lib/python3.4/site-packages/hitchtest/commandline.py", line 84, in run
    cli()
  File "/tmp/django-remindme/.hitch/virtualenv/lib/python3.4/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/django-remindme/.hitch/virtualenv/lib/python3.4/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/tmp/django-remindme/.hitch/virtualenv/lib/python3.4/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/django-remindme/.hitch/virtualenv/lib/python3.4/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/tmp/django-remindme/.hitch/virtualenv/lib/python3.4/site-packages/hitchtest/commandline.py", line 65, in cli
    test_modules.append(module.Module(filename, settings_dict))
  File "/tmp/django-remindme/.hitch/virtualenv/lib/python3.4/site-packages/hitchtest/module.py", line 33, in __init__
    tmpl = env.get_template(path.split(filename)[1])
  File "/tmp/django-remindme/.hitch/virtualenv/lib/python3.4/site-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/tmp/django-remindme/.hitch/virtualenv/lib/python3.4/site-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/tmp/django-remindme/.hitch/virtualenv/lib/python3.4/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: simple_reminder.test
```

Also, I don't know if it's related or not, but running `hitch init` in the same directory returns `Error: No such command "init"`.

**Comment by crdoconnor** [comment]
Hi Eliot. Thank you for trying out Hitch!

It looks like you ran hitch init in the /tmp/django-remindme directory. It needs to be run in the /tmp/django-remindme/django-remindme-tests directory.

Try deleting the /tmp/django-remindme/.hitch/ directory and re-running hitch init in the /tmp/django-remindme/django-remindme-tests/ directory. After you've done that, run hitch test simple_reminder.test in the django-remindme-tests directory.

I'll update the app to give a clearer error message than the one you saw.

Please let me know if you have any more issues.

**Comment by agateblue** [comment]
Thank you, it was indeed my bad. Removing the `.hitch` directory and running `hitch init` in the correct directory launched the test command correctly.

**Comment by crdoconnor** [comment]
Fix for unclear error message when no test found:

https://github.com/hitchtest/hitchtest/commit/46f15a300054d4645eb6f14729e0621985992b55

Fix for unclear error message when a .hitch directory was already initialized:

https://github.com/hitchtest/hitch/commit/d7da9ff75fa55ea4764ec6b83e6f5b476ed6a36f

Thanks once again for reporting this.
